pipeline{
    agent any
        stages {
            stage ('install') {
                steps {
                    dir("React-App"){
                        sh "npm install"
                    }
                }
            }
        
            stage ('build') {
                steps {
                    dir("React-App"){
                        sh "npm run build"
                    }
                }
            }

            stage ('test') {
                steps {
                    dir("React-App"){
                        sh "npm run test App -- --watchAll=false --ci --reporters=default --reporters=jest-junit --coverage --coverageReporters=cobertura"
                    }
                }
            }

        
        }
}