pieline{
    agent {label 'master'}
        stages {
            stage ('install') {
                steps {
                    dir("React-App"){
                        sh "npm install"
                    }
                }
            }
        }
}